import type { OpportunityRow } from "../supabase/functions/_shared/types.ts";

export function opportunityFixture(overrides: Partial<OpportunityRow> = {}): OpportunityRow {
  return {
    id: "12345678-1234-1234-1234-123456789abc",
    public_id: 12,
    draft_save_token: "87654321-4321-4321-4321-cba987654321",
    name: "Robotics Internship",
    organization: "Example Labs",
    normalized_name: "robotics internship",
    normalized_organization: "example labs",
    category: "internship",
    source_url: "https://example.com/internship",
    source_text: "Robotics Internship",
    discovered_on: "2026-09-09",
    status: "saved",
    status_confirmed_at: null,
    deadline_at: null,
    deadline_raw: null,
    deadline_precision: null,
    event_at: null,
    event_raw: null,
    event_precision: null,
    next_action: null,
    next_action_at: null,
    next_action_at_raw: null,
    next_action_at_precision: null,
    reminder_at: null,
    reminder_raw: null,
    reminder_precision: null,
    notes: null,
    outcome: null,
    last_activity_at: null,
    course_inactivity_days: 7,
    archived_at: null,
    created_at: "2026-09-09T08:00:00.000Z",
    updated_at: "2026-09-09T08:00:00.000Z",
    ...overrides,
  };
}
