-- Daily official-source discovery candidates. Nothing is added to the inbox
-- until Yusuf presses Save in Telegram.

create table if not exists public.opportunity_discovery_candidates (
  id uuid primary key default gen_random_uuid(),
  public_id bigint generated by default as identity unique not null,
  save_token uuid not null default gen_random_uuid() unique,
  source_key text not null unique,
  source_url text not null unique,
  source_name text not null,
  name text not null,
  organization text not null,
  category text not null
    check (category in ('job', 'internship', 'program', 'event', 'course', 'competition', 'hackathon')),
  source_text text not null default '',
  deadline_at timestamptz,
  deadline_raw text,
  deadline_precision text check (deadline_precision in ('date', 'datetime')),
  event_at timestamptz,
  event_raw text,
  event_precision text check (event_precision in ('date', 'datetime')),
  next_action text,
  notes text,
  status text not null default 'new'
    check (status in ('new', 'sending', 'sent', 'failed', 'unknown', 'saved', 'dismissed', 'expired')),
  attempt_count smallint not null default 0 check (attempt_count between 0 and 3),
  claimed_at timestamptz,
  sent_at timestamptz,
  telegram_message_id bigint,
  error_message text,
  opportunity_id uuid references public.opportunities(id) on delete set null,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint opportunity_discovery_source_url_http check (source_url ~ '^https?://'),
  constraint opportunity_discovery_nonempty check (
    btrim(name) <> '' and btrim(organization) <> '' and btrim(source_name) <> ''
  ),
  constraint opportunity_discovery_date_metadata check (
    (deadline_at is null) = (deadline_precision is null)
    and (event_at is null) = (event_precision is null)
  )
);

create index if not exists opportunity_discovery_status_idx
  on public.opportunity_discovery_candidates (status, created_at);

create or replace function public.claim_opportunity_discovery_candidate(p_candidate_id uuid)
returns table (claimed boolean, reason text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_updated integer;
begin
  update public.opportunity_discovery_candidates
  set status = 'sending',
      attempt_count = attempt_count + 1,
      claimed_at = now(),
      error_message = null,
      updated_at = now()
  where id = p_candidate_id
    and (
      status = 'new'
      or (status = 'failed' and attempt_count < 3 and claimed_at < now() - interval '15 minutes')
    );
  get diagnostics v_updated = row_count;
  if v_updated = 1 then
    return query select true, 'claimed'::text;
  else
    return query select false, 'not_available'::text;
  end if;
end;
$$;

alter table public.opportunity_discovery_candidates enable row level security;
revoke all on table public.opportunity_discovery_candidates from anon, authenticated;
revoke all on sequence public.opportunity_discovery_candidates_public_id_seq from anon, authenticated;
revoke all on function public.claim_opportunity_discovery_candidate(uuid) from public, anon, authenticated;
grant select, insert, update, delete on table public.opportunity_discovery_candidates to service_role;
grant usage, select on sequence public.opportunity_discovery_candidates_public_id_seq to service_role;
grant execute on function public.claim_opportunity_discovery_candidate(uuid) to service_role;

create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;

do $$
declare
  v_job_id bigint;
begin
  for v_job_id in
    select jobid from cron.job where jobname = 'opportunity-inbox-daily-discovery'
  loop
    perform cron.unschedule(v_job_id);
  end loop;

  perform cron.schedule(
    'opportunity-inbox-daily-discovery',
    '0 4 * * *',
    $command$
      select net.http_post(
        url := (select decrypted_secret from vault.decrypted_secrets
          where name = 'opportunity_inbox_project_url'
          order by created_at desc limit 1)
          || '/functions/v1/opportunity-discovery',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-cron-secret', (select decrypted_secret from vault.decrypted_secrets
            where name = 'opportunity_inbox_cron_secret'
            order by created_at desc limit 1)
        ),
        body := '{}'::jsonb,
        timeout_milliseconds := 120000
      );
    $command$
  );
end;
$$;
