-- Private, single-user Opportunity Inbox.
-- Edge Functions use the Supabase server secret. Browser access is denied.

create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),
  public_id bigint generated by default as identity unique not null,
  draft_save_token uuid not null unique,
  name text not null,
  organization text,
  normalized_name text not null,
  normalized_organization text not null default '',
  category text not null default 'other'
    check (category in ('job', 'internship', 'course', 'program', 'competition', 'hackathon', 'event', 'other')),
  source_url text,
  source_text text not null default '',
  discovered_on date not null default ((now() at time zone 'Asia/Dubai')::date),
  status text not null default 'saved'
    check (status in (
      'saved', 'planning', 'applied', 'registered', 'waiting',
      'accepted', 'rejected', 'in_progress', 'completed'
    )),
  status_confirmed_at timestamptz,
  deadline_at timestamptz,
  deadline_raw text,
  deadline_precision text check (deadline_precision in ('date', 'datetime')),
  event_at timestamptz,
  event_raw text,
  event_precision text check (event_precision in ('date', 'datetime')),
  next_action text,
  next_action_at timestamptz,
  next_action_at_raw text,
  next_action_at_precision text check (next_action_at_precision in ('date', 'datetime')),
  reminder_at timestamptz,
  reminder_raw text,
  reminder_precision text check (reminder_precision in ('date', 'datetime')),
  notes text,
  outcome text,
  last_activity_at timestamptz,
  course_inactivity_days smallint not null default 7
    check (course_inactivity_days between 1 and 365),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint opportunities_nonempty_name check (btrim(name) <> ''),
  constraint opportunities_source_url_http check (
    source_url is null or source_url ~ '^https?://'
  ),
  constraint opportunities_source_size check (char_length(source_text) <= 8000),
  constraint opportunities_text_sizes check (
    char_length(name) <= 180
    and (organization is null or char_length(organization) <= 160)
    and (next_action is null or char_length(next_action) <= 1000)
    and (notes is null or char_length(notes) <= 4000)
    and (outcome is null or char_length(outcome) <= 2000)
  ),
  constraint opportunities_date_metadata check (
    (deadline_at is null) = (deadline_precision is null)
    and (event_at is null) = (event_precision is null)
    and (next_action_at is null) = (next_action_at_precision is null)
    and (reminder_at is null) = (reminder_precision is null)
  ),
  -- Pasted text and parsers cannot claim a lifecycle event. A non-draft
  -- status is valid only after an explicit user action records confirmation.
  constraint opportunities_status_requires_confirmation check (
    status in ('saved', 'planning') or status_confirmed_at is not null
  )
);

create index if not exists opportunities_active_updated_idx
  on public.opportunities (updated_at desc)
  where archived_at is null;
create index if not exists opportunities_deadline_idx
  on public.opportunities (deadline_at)
  where archived_at is null and deadline_at is not null;
create index if not exists opportunities_event_idx
  on public.opportunities (event_at)
  where archived_at is null and event_at is not null;
create index if not exists opportunities_reminder_idx
  on public.opportunities (reminder_at)
  where archived_at is null and reminder_at is not null;
create index if not exists opportunities_normalized_idx
  on public.opportunities (normalized_name, normalized_organization);

create table if not exists public.opportunity_bot_sessions (
  chat_id text primary key,
  mode text not null default 'idle'
    check (mode in ('idle', 'await_draft', 'review_draft', 'draft_field', 'item_field')),
  draft jsonb,
  pending_field text,
  editing_public_id bigint,
  preview_message_id bigint,
  updated_at timestamptz not null default now(),
  constraint opportunity_session_shape check (
    (mode in ('review_draft', 'draft_field') and draft is not null)
    or (mode not in ('review_draft', 'draft_field'))
  )
);

create table if not exists public.opportunity_telegram_updates (
  update_id bigint primary key,
  status text not null default 'processing'
    check (status in ('processing', 'processed', 'failed')),
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.opportunity_reminder_deliveries (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references public.opportunities(id) on delete cascade,
  reminder_key text not null,
  reminder_kind text not null
    check (reminder_kind in ('manual', 'next_action', 'deadline', 'event', 'overdue', 'course_inactivity')),
  due_at timestamptz not null,
  status text not null default 'claimed'
    check (status in ('claimed', 'sent', 'failed', 'unknown')),
  claim_token uuid not null default gen_random_uuid(),
  attempt_count smallint not null default 1 check (attempt_count between 1 and 3),
  telegram_message_id bigint,
  error_message text,
  claimed_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (opportunity_id, reminder_key)
);

create index if not exists opportunity_reminder_delivery_status_idx
  on public.opportunity_reminder_deliveries (status, claimed_at desc);

create or replace function public.claim_opportunity_reminder(
  p_opportunity_id uuid,
  p_reminder_key text,
  p_reminder_kind text,
  p_due_at timestamptz
)
returns table (claimed boolean, delivery_id uuid, delivery_token uuid, reason text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id uuid;
  v_token uuid := gen_random_uuid();
begin
  insert into public.opportunity_reminder_deliveries (
    opportunity_id, reminder_key, reminder_kind, due_at, claim_token
  ) values (
    p_opportunity_id, p_reminder_key, p_reminder_kind, p_due_at, v_token
  )
  on conflict (opportunity_id, reminder_key) do nothing
  returning id into v_id;

  if v_id is not null then
    return query select true, v_id, v_token, 'new'::text;
    return;
  end if;

  update public.opportunity_reminder_deliveries
  set status = 'claimed',
      claim_token = v_token,
      attempt_count = attempt_count + 1,
      claimed_at = now(),
      completed_at = null,
      error_message = null
  where opportunity_id = p_opportunity_id
    and reminder_key = p_reminder_key
    and status = 'failed'
    and attempt_count < 3
    and claimed_at < now() - interval '15 minutes'
  returning id into v_id;

  if v_id is not null then
    return query select true, v_id, v_token, 'retry'::text;
    return;
  end if;

  -- A stale claim may have reached Telegram before its database response was
  -- lost. Mark it uncertain instead of sending the notification again.
  update public.opportunity_reminder_deliveries
  set status = 'unknown',
      error_message = coalesce(error_message, 'Delivery result was not safely recorded; not retried.'),
      completed_at = now()
  where opportunity_id = p_opportunity_id
    and reminder_key = p_reminder_key
    and status = 'claimed'
    and claimed_at < now() - interval '30 minutes';

  select id into v_id
  from public.opportunity_reminder_deliveries
  where opportunity_id = p_opportunity_id and reminder_key = p_reminder_key;
  return query select false, v_id, null::uuid, 'duplicate'::text;
end;
$$;

create or replace function public.finish_opportunity_reminder(
  p_delivery_id uuid,
  p_claim_token uuid,
  p_status text,
  p_message_id bigint default null,
  p_error text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_updated integer;
begin
  if p_status not in ('sent', 'failed', 'unknown') then
    raise exception 'Invalid reminder result';
  end if;
  update public.opportunity_reminder_deliveries
  set status = p_status,
      telegram_message_id = p_message_id,
      error_message = left(p_error, 500),
      completed_at = now()
  where id = p_delivery_id
    and claim_token = p_claim_token
    and status = 'claimed';
  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

create or replace function public.claim_opportunity_telegram_update(p_update_id bigint)
returns table (claimed boolean, reason text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_inserted integer;
  v_status text;
  v_started_at timestamptz;
begin
  if p_update_id is null or p_update_id < 0 then
    raise exception 'A valid update ID is required';
  end if;
  insert into public.opportunity_telegram_updates (update_id)
  values (p_update_id)
  on conflict (update_id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 1 then
    return query select true, 'new'::text;
    return;
  end if;

  select status, started_at into v_status, v_started_at
  from public.opportunity_telegram_updates
  where update_id = p_update_id;

  if v_status = 'processing' and v_started_at < now() - interval '10 minutes' then
    update public.opportunity_telegram_updates
    set status = 'failed',
        error_message = 'The worker stopped before completion; manual review is required.',
        completed_at = now()
    where update_id = p_update_id and status = 'processing';
    return query select false, 'stale_review_required'::text;
    return;
  end if;

  return query select false, coalesce(v_status, 'duplicate')::text;
end;
$$;

create or replace function public.finish_opportunity_telegram_update(
  p_update_id bigint,
  p_status text,
  p_error text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_updated integer;
begin
  if p_status not in ('processed', 'failed') then
    raise exception 'Invalid final update status';
  end if;
  update public.opportunity_telegram_updates
  set status = p_status,
      error_message = left(p_error, 500),
      completed_at = now()
  where update_id = p_update_id and status = 'processing';
  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

create or replace function public.set_opportunity_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists opportunities_set_updated_at on public.opportunities;
create trigger opportunities_set_updated_at
before update on public.opportunities
for each row execute function public.set_opportunity_updated_at();

alter table public.opportunities enable row level security;
alter table public.opportunity_bot_sessions enable row level security;
alter table public.opportunity_telegram_updates enable row level security;
alter table public.opportunity_reminder_deliveries enable row level security;

revoke all on table public.opportunities from anon, authenticated;
revoke all on table public.opportunity_bot_sessions from anon, authenticated;
revoke all on table public.opportunity_telegram_updates from anon, authenticated;
revoke all on table public.opportunity_reminder_deliveries from anon, authenticated;
revoke all on sequence public.opportunities_public_id_seq from anon, authenticated;
revoke all on function public.claim_opportunity_telegram_update(bigint) from public, anon, authenticated;
revoke all on function public.finish_opportunity_telegram_update(bigint, text, text) from public, anon, authenticated;
revoke all on function public.claim_opportunity_reminder(uuid, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.finish_opportunity_reminder(uuid, uuid, text, bigint, text) from public, anon, authenticated;

grant select, insert, update, delete on table public.opportunities to service_role;
grant select, insert, update, delete on table public.opportunity_bot_sessions to service_role;
grant select, insert, update, delete on table public.opportunity_telegram_updates to service_role;
grant select, insert, update, delete on table public.opportunity_reminder_deliveries to service_role;
grant usage, select on sequence public.opportunities_public_id_seq to service_role;
grant execute on function public.claim_opportunity_telegram_update(bigint) to service_role;
grant execute on function public.finish_opportunity_telegram_update(bigint, text, text) to service_role;
grant execute on function public.claim_opportunity_reminder(uuid, text, text, timestamptz) to service_role;
grant execute on function public.finish_opportunity_reminder(uuid, uuid, text, bigint, text) to service_role;
